[package]
name = "tmnt"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"

[dependencies]
chrono = "0.4.22"
serenity = { version = "0.11.5", features = ["http", "model", "rustls_backend"] }
tokio = { version = "1.20.4", features = ["rt", "macros", "time"] }
